<div>
    @if($status->attachment?->exists)
        <div class="bg-white dark:bg-gray-700 p-4 my-3 rounded-md shadow-xs">
            <audio controls src="{{ Storage::url($status->attachment->file) }}"></audio>
            <span class="text-gray-500 dark:text-gray-300 text-xs">Generated by OpenAI API.</span>
        </div>
    @endif

    @can('admin')
        <div>
            <x-secondary-button wire:click="create" class="px-6">
                {{ __('音声ファイルを生成') }}
            </x-secondary-button>
            @if($status->attachment?->exists)
                <x-danger-button wire:click="delete" wire:confirm="削除しますか？" class="px-6">
                    {{ __('削除') }}
                </x-danger-button>
            @endif
        </div>
    @endcan
</div>
